"use client";

import React, { useState, useEffect, useCallback } from "react";
import {
  CheckCircle2, ChevronDown, ChevronRight, Shield, Wand2,
  ToggleLeft, ToggleRight, Save,
} from "lucide-react";
import { useAuth } from "@/lib/auth-context";
import { brand } from "@/lib/brand";

/* ─── i18n ─────────────────────────────────────────────────────────────────── */

type Lang = "en" | "pt";

const WIZARD_COPY = {
  en: {
    subtitle:     "AI assistant to configure your factory. Consumes credits from your accounts.",
    badgeOn:      "Enabled",
    badgeOff:     "Disabled",
    consentTitle: "Cost notice",
    consentP1:    <>The Wizard uses your own AI models. Each conversation may make multiple API calls, billed to your chosen provider&apos;s account. <strong>{brand.name} is not responsible for these costs.</strong></>,
    consentP2:    "You can set an estimated monthly limit below. You'll be notified when you reach it — but it's your responsibility to monitor billing in your provider's dashboard.",
    cancel:       "Cancel",
    acceptWizard: "I understand, enable Wizard",
    toggleLabel:  "Enable Wizard",
    toggleSub:    "Displays the magic wand button in Studio",
    limitLabel:   "Estimated monthly limit (USD)",
    limitHint:    "Declarative — you'll be notified when you reach the limit",
    noLimit:      "No limit set — monitor billing directly in your provider's dashboard.",
    disclaimer:   `${brand.name} is not responsible for costs generated by the Wizard. Each call is charged to your provider accounts.`,
    savedLabel:   "Saved",
    saveLabel:    "Save",
  },
  pt: {
    subtitle:     "Assistente de IA para configurar sua factory. Consome créditos das suas contas.",
    badgeOn:      "Habilitado",
    badgeOff:     "Desabilitado",
    consentTitle: "Aviso de custo",
    consentP1:    <>O Wizard usa seus próprios modelos de IA. Cada conversa pode fazer múltiplas chamadas de API, cobradas na sua conta do provedor escolhido. <strong>A {brand.name} não se responsabiliza por esses custos.</strong></>,
    consentP2:    "Você pode definir um limite mensal estimado abaixo. Ao atingi-lo, você será alertado — mas é sua responsabilidade controlar o billing no painel do provedor.",
    cancel:       "Cancelar",
    acceptWizard: "Entendi, habilitar Wizard",
    toggleLabel:  "Habilitar Wizard",
    toggleSub:    "Exibe o botão de varinha mágica no Studio",
    limitLabel:   "Limite mensal estimado (USD)",
    limitHint:    "Declarativo — você será alertado ao atingir o limite",
    noLimit:      "Sem limite definido — acompanhe o billing diretamente no painel do provedor.",
    disclaimer:   `A ${brand.name} não se responsabiliza por custos gerados pelo Wizard. Cada chamada é cobrada nas suas contas de provedor.`,
    savedLabel:   "Salvo",
    saveLabel:    "Salvar",
  },
} as const;

function useLang(): [Lang, (l: Lang) => void] {
  const [lang, setLangState] = useState<Lang>("en");
  useEffect(() => {
    const stored = localStorage.getItem("tirsa_lang");
    if (stored === "en" || stored === "pt") setLangState(stored as Lang);
  }, []);
  const setLang = useCallback((l: Lang) => {
    setLangState(l);
    localStorage.setItem("tirsa_lang", l);
  }, []);
  return [lang, setLang];
}

function LangToggle({ lang, onChange }: { lang: Lang; onChange: (l: Lang) => void }) {
  return (
    <div style={{ display: "flex", gap: 4 }}>
      {(["en", "pt"] as Lang[]).map((l) => (
        <button
          key={l}
          onClick={() => onChange(l)}
          title={l === "en" ? "English" : "Português"}
          style={{
            background: lang === l ? "var(--surface1)" : "transparent",
            border: lang === l ? "1px solid var(--surface2)" : "1px solid transparent",
            borderRadius: 6, padding: "2px 6px", cursor: "pointer",
            fontSize: 16, lineHeight: 1, opacity: lang === l ? 1 : 0.45,
            transition: "all 0.15s",
          }}
        >{l === "en" ? "🇬🇧" : "🇧🇷"}</button>
      ))}
    </div>
  );
}

/* ─── Constants ─────────────────────────────────────────────────────────────── */

// Same key used by WizardPanel to persist selected model
export const WIZARD_MODEL_KEY = "tirsa_wizard_model";

interface WizardLiveProvider { id: string; name: string; models: { id: string; name: string }[] }

/* ─── WizardSection ─────────────────────────────────────────────────────────── */

export function WizardSection({ tenantId, collapsible = true }: { tenantId: string; collapsible?: boolean }) {
  const enabledKey = `tirsa_wizard_enabled_${tenantId}`;
  const limitKey   = `tirsa_wizard_limit_${tenantId}`;

  const [open,        setOpen]        = useState(!collapsible);
  const [enabled,     setEnabled]     = useState(false);
  const [limit,       setLimit]       = useState("");
  const [saved,       setSaved]       = useState(false);
  const [showConsent, setShowConsent] = useState(false);
  const [lang, setLang] = useLang();

  // LLM default for Wizard
  const [providers,   setProviders]   = useState<WizardLiveProvider[]>([]);
  const [wizProvider, setWizProvider] = useState("");
  const [wizModel,    setWizModel]    = useState("");
  const [modelSaved,  setModelSaved]  = useState(false);
  const { session: authSession } = useAuth();

  useEffect(() => {
    setEnabled(localStorage.getItem(enabledKey) === "true");
    setLimit(localStorage.getItem(limitKey) ?? "");
    try {
      const stored = localStorage.getItem(WIZARD_MODEL_KEY);
      if (stored) {
        const { provider, model } = JSON.parse(stored) as { provider: string; model: string };
        setWizProvider(provider);
        setWizModel(model);
      }
    } catch { /* ignore */ }
  }, [enabledKey, limitKey]);

  useEffect(() => {
    if (!authSession) return;
    fetch("/api/wizard/models", { headers: { Authorization: `Bearer ${authSession.access_token}` } })
      .then(async (res) => {
        if (res.ok) {
          const body = await res.json() as { providers: WizardLiveProvider[] };
          setProviders(body.providers ?? []);
        }
      });
  }, [authSession]);

  function saveWizardModel() {
    if (!wizProvider) return;
    try {
      localStorage.setItem(WIZARD_MODEL_KEY, JSON.stringify({ provider: wizProvider, model: wizModel }));
    } catch { /* ignore */ }
    setModelSaved(true);
    setTimeout(() => setModelSaved(false), 2000);
  }

  const t = WIZARD_COPY[lang];

  function handleToggle() {
    if (!enabled) {
      setShowConsent(true);
    } else {
      setEnabled(false);
      localStorage.setItem(enabledKey, "false");
    }
  }

  function acceptConsent() {
    setShowConsent(false);
    setEnabled(true);
    localStorage.setItem(enabledKey, "true");
    localStorage.setItem(`tirsa_wizard_consent_${tenantId}`, new Date().toISOString());
  }

  function saveLimit() {
    const v = limit.trim();
    if (v) localStorage.setItem(limitKey, v);
    else localStorage.removeItem(limitKey);
    setSaved(true);
    setTimeout(() => setSaved(false), 2000);
  }

  return (
    <div>
      {collapsible && (
        <>
          <button
            onClick={() => setOpen((o) => !o)}
            style={{ width: "100%", display: "flex", alignItems: "center", gap: 10, background: "transparent", border: "none", cursor: "pointer", padding: "6px 0", marginBottom: 10, textAlign: "left" }}
          >
            <div style={{ color: "var(--overlay1)" }}><Wand2 size={15} /></div>
            <div style={{ flex: 1 }}>
              <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                <span style={{ fontSize: 13, fontWeight: 700, color: "var(--text)" }}>Wizard</span>
                <span style={{
                  fontSize: 10, fontWeight: 700, padding: "1px 7px", borderRadius: 99,
                  background: enabled ? "rgba(28,191,107,0.12)" : "var(--surface1)",
                  color: enabled ? "var(--green)" : "var(--overlay0)",
                }}>
                  {enabled ? t.badgeOn : t.badgeOff}
                </span>
              </div>
              <div style={{ fontSize: 11, color: "var(--subtext0)", marginTop: 1 }}>{t.subtitle}</div>
            </div>
            {open ? <ChevronDown size={15} color="var(--overlay0)" /> : <ChevronRight size={15} color="var(--overlay0)" />}
          </button>
          <div style={{ height: 1, background: "var(--surface0)", marginBottom: 10 }} />
        </>
      )}

      {open && (
        <div style={{ background: "var(--mantle)", border: "1px solid var(--surface1)", borderRadius: 12, padding: "16px" }}>
          {showConsent ? (
            <div>
              <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 14 }}>
                <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                  <Shield size={15} color="#1463ff" />
                  <span style={{ fontSize: 13, fontWeight: 700 }}>{t.consentTitle}</span>
                </div>
                <LangToggle lang={lang} onChange={setLang} />
              </div>
              <p style={{ fontSize: 12, color: "var(--subtext1)", lineHeight: 1.7, marginBottom: 12 }}>{t.consentP1}</p>
              <p style={{ fontSize: 12, color: "var(--subtext1)", lineHeight: 1.7, marginBottom: 16 }}>{t.consentP2}</p>
              <div style={{ display: "flex", gap: 8 }}>
                <button
                  onClick={() => setShowConsent(false)}
                  style={{ flex: 1, padding: "9px", borderRadius: 8, border: "1px solid var(--surface2)", background: "transparent", color: "var(--subtext0)", fontSize: 12, fontWeight: 600, cursor: "pointer", fontFamily: "var(--font-sans)" }}
                >
                  {t.cancel}
                </button>
                <button
                  onClick={acceptConsent}
                  style={{ flex: 2, padding: "9px", borderRadius: 8, border: "none", background: "#1463ff", color: "#fff", fontSize: 12, fontWeight: 700, cursor: "pointer", fontFamily: "var(--font-sans)" }}
                >
                  {t.acceptWizard}
                </button>
              </div>
            </div>
          ) : (
            <>
              <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: enabled ? 16 : 0 }}>
                <div>
                  <div style={{ fontSize: 13, fontWeight: 600 }}>{t.toggleLabel}</div>
                  <div style={{ fontSize: 11, color: "var(--overlay0)", marginTop: 2 }}>{t.toggleSub}</div>
                </div>
                <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                  <LangToggle lang={lang} onChange={setLang} />
                  <button
                    onClick={handleToggle}
                    style={{ background: "none", border: "none", cursor: "pointer", color: enabled ? "var(--green)" : "var(--overlay1)", padding: 4, display: "flex" }}
                    title={enabled ? "Disable Wizard" : "Enable Wizard"}
                  >
                    {enabled ? <ToggleRight size={28} /> : <ToggleLeft size={28} />}
                  </button>
                </div>
              </div>

              {enabled && (
                <>
                  <div style={{ height: 1, background: "var(--surface0)", marginBottom: 14 }} />

                  {/* Default LLM / Model */}
                  <div style={{ marginBottom: 14 }}>
                    <label style={{ display: "block", fontSize: 11, fontWeight: 600, color: "var(--subtext1)", marginBottom: 6 }}>
                      Default LLM
                      <span style={{ fontSize: 10, fontWeight: 400, color: "var(--overlay0)", marginLeft: 8 }}>used by the Wizard when opened</span>
                    </label>
                    {providers.length === 0 ? (
                      <div style={{ fontSize: 12, color: "var(--overlay0)" }}>No providers configured. <a href="/providers" style={{ color: "var(--blue)" }}>Add an API key.</a></div>
                    ) : (
                      <div style={{ display: "flex", gap: 8 }}>
                        <select
                          value={wizProvider}
                          onChange={(e) => { setWizProvider(e.target.value); setWizModel(providers.find((p) => p.id === e.target.value)?.models[0]?.id ?? ""); }}
                          style={{ flex: "0 0 160px", padding: "7px 10px", background: "var(--surface0)", border: "1px solid var(--surface1)", borderRadius: 8, color: "var(--text)", fontSize: 13, outline: "none", fontFamily: "var(--font-sans)" }}
                        >
                          <option value="">— choose —</option>
                          {providers.map((p) => <option key={p.id} value={p.id}>{p.name || p.id}</option>)}
                        </select>
                        <select
                          value={wizModel}
                          onChange={(e) => setWizModel(e.target.value)}
                          disabled={!wizProvider}
                          style={{ flex: 1, padding: "7px 10px", background: "var(--surface0)", border: "1px solid var(--surface1)", borderRadius: 8, color: "var(--text)", fontSize: 13, outline: "none", fontFamily: "var(--font-sans)" }}
                        >
                          <option value="">— default for provider —</option>
                          {(providers.find((p) => p.id === wizProvider)?.models ?? []).map((m) => <option key={m.id} value={m.id}>{m.id}</option>)}
                        </select>
                        <button
                          onClick={saveWizardModel}
                          disabled={!wizProvider}
                          style={{ display: "flex", alignItems: "center", gap: 6, padding: "8px 14px", borderRadius: 8, border: "none", background: modelSaved ? "rgba(28,191,107,0.15)" : "#1463ff", color: modelSaved ? "var(--green)" : "#fff", fontSize: 12, fontWeight: 600, cursor: wizProvider ? "pointer" : "default", opacity: wizProvider ? 1 : 0.5, fontFamily: "var(--font-sans)", whiteSpace: "nowrap" }}
                        >
                          {modelSaved ? <><CheckCircle2 size={12} /> Saved</> : <><Save size={12} /> Save</>}
                        </button>
                      </div>
                    )}
                  </div>

                  <div style={{ height: 1, background: "var(--surface0)", marginBottom: 14 }} />

                  {/* Monthly limit */}
                  <div>
                    <label style={{ display: "block", fontSize: 11, fontWeight: 600, color: "var(--subtext1)", marginBottom: 4 }}>
                      {t.limitLabel}
                      <span style={{ fontSize: 10, fontWeight: 400, color: "var(--overlay0)", marginLeft: 8 }}>{t.limitHint}</span>
                    </label>
                    <div style={{ display: "flex", gap: 8 }}>
                      <input
                        type="number" min="0" step="5" placeholder="e.g. 20"
                        value={limit}
                        onChange={(e) => setLimit(e.target.value)}
                        style={{ flex: 1, padding: "8px 12px", background: "var(--surface0)", border: "1px solid var(--surface1)", borderRadius: 8, color: "var(--text)", fontSize: 13, outline: "none", fontFamily: "var(--font-sans)" }}
                      />
                      <button
                        onClick={saveLimit}
                        style={{ display: "flex", alignItems: "center", gap: 6, padding: "8px 16px", borderRadius: 8, border: "none", background: saved ? "rgba(28,191,107,0.15)" : "#1463ff", color: saved ? "var(--green)" : "#fff", fontSize: 12, fontWeight: 600, cursor: "pointer", fontFamily: "var(--font-sans)", whiteSpace: "nowrap" }}
                      >
                        {saved ? <><CheckCircle2 size={12} /> {t.savedLabel}</> : <><Save size={12} /> {t.saveLabel}</>}
                      </button>
                    </div>
                    {!limit && (
                      <div style={{ fontSize: 11, color: "var(--overlay0)", marginTop: 6 }}>{t.noLimit}</div>
                    )}
                  </div>
                  <div style={{ marginTop: 14, padding: "8px 12px", borderRadius: 8, background: "rgba(107,122,158,0.08)", border: "1px solid var(--surface1)", fontSize: 11, color: "var(--overlay1)", lineHeight: 1.6 }}>
                    <Shield size={10} style={{ display: "inline", verticalAlign: "middle", marginRight: 5 }} />
                    {t.disclaimer}
                  </div>
                </>
              )}
            </>
          )}
        </div>
      )}
    </div>
  );
}
